# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc113cef85cf6d14332b38843fdfe0de68bbbb23d55b934f88e360174740531c5dab0ed6f8a1d6dd51772b23492b2c1fdb725691ecdee6061643b0b4558bb010

test:
  secret_key_base: dbcf57ccece7826fc929043262712291535912982edaa89ffea8d0123d2ec32f77f8cdd47e504146d1b3125e478f149764145e4fdc3136182bf392877b489f7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
